spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/youtu?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    mvc:
        static-path-pattern: /res/**
    servlet:
        multipart:
            max-request-size: 10MB  # 上传文件的总的最大值
            max-file-size: 1MB      # 单个文件的最大值
    web:
        resources:
            static-locations: classpath:public/,file:public/
    jackson:
        default-property-inclusion: non_null # 不返回null

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    type-enums-package: com.valid.youtu.enums

server:
    servlet:
        context-path: /youtu/api
    port: 8080