spring:
    mvc:
        static-path-pattern: /res/**
    servlet:
        multipart:
            max-request-size: 10MB  # 上传文件的总的最大值
            max-file-size: 1MB      # 单个文件的最大值
    web:
        resources:
            static-locations: classpath:public/,file:public/
    jackson:
        default-property-inclusion: non_null # 不返回null
    profiles:
        active: dev

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    type-enums-package: com.valid.youtu.enums

server:
    servlet:
        context-path: /youtu/api
    port: 8080